AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/devise.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 162

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/yarn'
    - 'config/puma.rb'
    - 'db/schema.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'config/environments/development.rb'
    - 'db/seeds.rb'
    - 'spec/controllers/students_controller_spec.rb'
    - 'spec/controllers/users_controller_spec.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'spec/rails_helper.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'